	Pascal-compiler error message texts
  1 : Error in a simple type
  2 : The name is expected
  3 : PROGRAM is expected
  4 : ')' is expected
  5 : ':' is expected
  6 : Forbidden character
  7 : Error in parameter list
  8 : OF is expected
  9 : '(' is expected
 10 : Simple type error
 11 : '['  is expected
 12 : ']'  is expected
 13 : END is expected
 14 : ';'  is expected
 15 : integer is expected
 16 : '=' is expected
 17 : BEGIN is expected
 18 : Error in declaration part
 19 : Error in fields list
 20 :  ',' is expected
 21 : Error in the variable
 50 : Error in the constant
 51 : ':=' is expected
 52 : THEN is expected
 53 : UNTIL is expected
 54 : DO is expected
 55 : TO  or  DOWNTO is expected
 56 : IF is expected
 61 : '.' is expected
 74 : '..' is expected
 75 : Error in the char constant
 76 : Too long string constant
 86 : Comment is not closed
100 : The use of a name does not match the description
101 : Name is redeclared
102 : The lower limit exceeds the upper limit
104 : Name is not declared
105 : Invalid recursive definition
108 : File can not be used here
109 : Type must not be  REAL
111 : Incompatibility with discriminant type
112 : Invalid limited type
114 : Basis type should not be REAL	or INTEGER
115 : The file must be a text file
116 : Error in the type of the standard procedure parameter
117 : Improper forward description
118 : An invalid type of the sign of the variant part of the record
119 : Forward description: it is not allowed to repeat the parameter list
120 : The result type of the function must be scalar, reference, or limited
121 : Parameter-value can not be a file
122 : Forward function description: the result type can not be repeated 
123 : In the function description the result type is missing
124 : F-format for REAL only
125 : Error in the type of the standard function parameter
126 : The number of parameters does not match the description
127 : Invalid parameter substitution
128 : The type of the result of the function does not match the description
130 : The expression does not apply to the set type
135 : Type of operand must be BOOLEAN
137 : Invalid types of elements of the set
138 : The variable is not an array
139 : The type of index does not match the description
140 : The variable is not a record
141 : The variable must be a file or a reference
142 : Invalid parameter substitution
143 : Invalid loop parameter type
144 : Invalid expression type
145 : Type conflict
147 : The type of the label does not match the type of the expression
149 : Type of index can not be REAL  or  INTEGER
152 : There is no such field in this record
156 : The variant label is defined several times
165 : The label is defined several times
166 : The label is described several times
167 : The label is not described
168 : Undefined label
169 : Error in the base of the set
170 : Type can not be packed
177 : It is not allowed to assign a function name
182 : Types are not compatible
183 : Prohibited operation in this context
184 : An element of this type can not have a sign
186 : Type mismatch for the operation of the relation
189 : Conflict of types of parameters
190 : Repeated advance description
191 : Error in constructor set
193 : An extra index for accessing an array element
194 : Too few indexes for accessing the array element195 : Constant out of the described range
196 : Invalid type of constant
197 : the parameters of the procedure (function) being a parameter must be parameters-values
198 : mismatch in the number of parameters of the parameter-procedure (function)
199 : mismatch between parameter types of a parameter-procedure (function)
200 : The type of the function function does not match the description
201 : error in the real constant: there must be a digit203 : Integer constant exceeds the limit
206 : Too small real constant
207 : Too large real constant
208 : invalid operand types in IN operation
209 : the second operand IN must be set
210 : the AND, NOT, OR operands must be Boolean
211 : Invalid operand types in the + or -
212 : The DIV and MOD operands must be integers
213 : invalid operand types in operation *
214 : invalid operand types in operation /
215 : the first operand IN must be an expression of the base type of the set
216 : there is a leading description, there is no complete description
305 : the index value is out of bounds
306 : the value assigned is out of bounds
307 : the expression for the set element is outside the range
308 : the expression is out of range
309 : the word EXPORT is expected
310 : the word IMPORT is expected
311 : the word INTERFACE  is expected
312 : the word IMPLEMENTATION is expected
313 : the word MODULE is expected
314 : too many labels